// AUTO-GENERATED by scripts/fetch-banners.mjs — do not edit by hand.
export const BANNERS: Record<string, string[]> = {
  "lottery-popup": [
    "/banners/lottery-popup-0.webp",
    "/banners/lottery-popup-1.webp",
    "/banners/lottery-popup-4.webp",
    "/banners/lottery-popup-5.webp",
    "/banners/lottery-popup-7.webp"
  ],
  "diet-miracle": [
    "/banners/diet-miracle-0.webp",
    "/banners/diet-miracle-1.webp",
    "/banners/diet-miracle-2.webp",
    "/banners/diet-miracle-3.webp",
    "/banners/diet-miracle-4.webp",
    "/banners/diet-miracle-5.webp"
  ],
  "predatory-loan": [
    "/banners/predatory-loan-0.webp",
    "/banners/predatory-loan-1.webp",
    "/banners/predatory-loan-2.webp",
    "/banners/predatory-loan-3.webp",
    "/banners/predatory-loan-4.webp",
    "/banners/predatory-loan-5.webp"
  ],
  "gambling": [
    "/banners/gambling-0.webp",
    "/banners/gambling-1.webp",
    "/banners/gambling-2.webp",
    "/banners/gambling-3.webp",
    "/banners/gambling-4.webp",
    "/banners/gambling-7.webp"
  ],
  "crypto-moon": [
    "/banners/crypto-moon-0.webp",
    "/banners/crypto-moon-1.webp",
    "/banners/crypto-moon-2.webp",
    "/banners/crypto-moon-3.webp",
    "/banners/crypto-moon-4.webp",
    "/banners/crypto-moon-5.webp"
  ],
  "sponsored-horoscope": [
    "/banners/sponsored-horoscope-0.webp",
    "/banners/sponsored-horoscope-1.webp",
    "/banners/sponsored-horoscope-2.webp",
    "/banners/sponsored-horoscope-3.webp",
    "/banners/sponsored-horoscope-4.webp",
    "/banners/sponsored-horoscope-5.webp",
    "/banners/sponsored-horoscope-6.webp",
    "/banners/sponsored-horoscope-7.webp"
  ]
};
