// Bake royalty-free object photos into public/banners + bannerManifest.ts.
// Run manually to refresh: `node scripts/fetch-banners.mjs`
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SECRET = "C:/Users/User/Desktop/project-365/.secret/env.local";
const OUT_DIR = join(ROOT, "public", "banners");
const MANIFEST = join(ROOT, "src", "lib", "bannerManifest.ts");
const PER_QUERY = 2;          // images to keep per query
const BANNED = /(person|people|man|woman|face|model|portrait|logo|brand|celebrity|player)/i;

function key(name) {
  const line = readFileSync(SECRET, "utf8").split(/\r?\n/).find((l) => l.startsWith(name + "="));
  if (!line) throw new Error(`missing ${name} in ${SECRET}`);
  return line.slice(name.length + 1).trim();
}

// Read templates without importing TS: parse id + imageQuery from the source.
// Bound each template to the segment between its own "id:" and the next one,
// so templates without imageQuery don't accidentally pick up a later template's.
function photoTemplates() {
  const src = readFileSync(join(ROOT, "src", "lib", "templates.ts"), "utf8");
  const idMatches = [...src.matchAll(/id:\s*"([^"]+)"/g)];
  const out = [];
  for (let i = 0; i < idMatches.length; i++) {
    const id = idMatches[i][1];
    const start = idMatches[i].index;
    const end = i + 1 < idMatches.length ? idMatches[i + 1].index : src.length;
    const segment = src.slice(start, end);
    const qm = segment.match(/imageQuery:\s*\[([^\]]+)\]/);
    if (!qm) continue;
    const queries = qm[1].split(",").map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
    out.push({ id, queries });
  }
  return out;
}

async function pexels(query, apiKey) {
  const url = `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=8&orientation=landscape`;
  const r = await fetch(url, { headers: { Authorization: apiKey } });
  if (!r.ok) throw new Error(`pexels ${r.status} for ${query}`);
  const j = await r.json();
  return (j.photos ?? []).filter((p) => !BANNED.test(p.alt ?? ""));
}

async function download(u) {
  const r = await fetch(u);
  if (!r.ok) throw new Error(`download ${r.status}`);
  return Buffer.from(await r.arrayBuffer());
}

async function main() {
  const apiKey = key("PEXELS_API_KEY");
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
  const manifest = {};
  for (const { id, queries } of photoTemplates()) {
    const files = [];
    let n = 0;
    for (const q of queries) {
      const photos = await pexels(q, apiKey);
      for (const p of photos.slice(0, PER_QUERY)) {
        // Pexels sized CDN variant (~800px, jpg). sharp→webp if present.
        const src = p.src.large; // ~940px
        const buf = await download(src);
        const rel = `/banners/${id}-${n}.webp`;
        let out = buf;
        try {
          const sharp = (await import("sharp")).default;
          out = await sharp(buf).resize(720, 720, { fit: "inside" }).webp({ quality: 62 }).toBuffer();
        } catch {
          // sharp unavailable: store as-is under .webp name is wrong; keep .jpg fallback
          const relJpg = `/banners/${id}-${n}.jpg`;
          writeFileSync(join(ROOT, "public", relJpg), buf);
          files.push(relJpg);
          n++;
          continue;
        }
        writeFileSync(join(ROOT, "public", rel), out);
        files.push(rel);
        n++;
      }
    }
    manifest[id] = files;
    console.log(`${id}: ${files.length} images`);
  }
  const body =
    "// AUTO-GENERATED by scripts/fetch-banners.mjs — do not edit by hand.\n" +
    "export const BANNERS: Record<string, string[]> = " +
    JSON.stringify(manifest, null, 2) +
    ";\n";
  writeFileSync(MANIFEST, body);
  console.log("wrote", MANIFEST);
}

main().catch((e) => { console.error(e); process.exit(1); });
